version: '3.9'
services:
  dsa-generator:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "dsa-generator"
    hostname: "dsa-generator"
    restart: "unless-stopped"
    ports:
      - 5000:5000