version: '3.9'
services:
  char-gen:
    build:
      context: ./
      dockerfile: Dockerfile
    container_name: "char-gen"
    hostname: "char-gen"
    restart: "unless-stopped"
    ports:
      - 8080:8080